export const FETCH_USER_DETAILS_BEGIN = 'FETCH_USER_DETAILS_BEGIN';
export const FETCH_USER_DETAILS_SUCCESS = 'FETCH_USER_DETAILS_SUCCESS';
export const FETCH_USER_DETAILS_ERROR = 'FETCH_USER_DETAILS_ERROR';
export const FETCH_MENU_DETAILS_BEGIN = 'FETCH_MENU_DETAILS_BEGIN';
export const FETCH_MENU_DETAILS_SUCCESS = 'FETCH_MENU_DETAILS_SUCCESS';
export const FETCH_MENU_DETAILS_ERROR = 'FETCH_MENU_DETAILS_ERROR';